theme: jekyll-theme-cayman
title: [Challenges in KDD and ML for Sustainable Development]
description: [Laure Berti-Equille (IRD) - David Dao (ETH Zürich) - Stefano Ermon (Stanford University) - Bedartha Goswami (University of Tübingen)]
github:
  is_project_page: false
